### PR TITLE
Use https:// instead of git:// for SCM URL

### PR DESCRIPTION
**Pull request by MarkEWaite**
https://github.blog/2021-09-01-improving-git-protocol-security-github/  announces that GitHub is turning off the unencrypted git:// protocol.

I'm not aware of any case that actually uses the URL, but better to start the repository with the http:// URL instead of git://

### CODE REVIEW

**Review by basil — APPROVED** [review]
Thank you!

**Comment by timja** [comment]
Lol this just made it into the hosting

**Comment by MarkEWaite** [comment]
That's great!  Do we need @basil to delete his fork so that the jenkinsci repo is the "one true repo"?  He can fork again after deleting, if I understand correctly.

**Comment by timja** [comment]
yes, it was only hosted 10 mins ago 😄

**Pull request merged**
